In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [120]:
ce = pd.read_csv('engineering.csv')

In [16]:
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource
from bokeh.palettes import Spectral5
from bokeh.plotting import figure
from bokeh.sampledata.autompg import autompg as df
from bokeh.transform import factor_cmap

In [121]:
for i in range(len(ce)):
    major = ce.loc[i, "Major"]
    if major == "BioE/MSE Joint Major":
        ce.loc[i, "Major"] = "BioE/MSE"
    elif major == "Bioengineering":
        ce.loc[i, "Major"] = "BioE"
    elif major == "Civil Engineering":
        ce.loc[i, "Major"] = "CivE"
    elif major == "EECS/MSE Joint Major":
        ce.loc[i, "Major"] = "EECS/MSE"
    elif major == "EECS/NE Joint Major":
        ce.loc[i, "Major"] = "EECS/NE"
    elif major == "Electrical Eng & Comp Sci":
        ce.loc[i, "Major"] = "EECS"
    elif major == "Energy Engineering":
        ce.loc[i, "Major"] = "EnergyE"
    elif major == "Eng Math & Statistics":
        ce.loc[i, "Major"] = "EngMathStats"
    elif major == "Engineering Physics":
        ce.loc[i, "Major"] = "EngPhys"
    elif major == "Environmental Eng Science":
        ce.loc[i, "Major"] == "EnvEngSci"
    elif major == "Industrial Eng & Ops Rsch":
        ce.loc[i, "Major"] = "IEOR"
    elif major == "ME/NE Joint Major":
        ce.loc[i, "Major"] = "ME/NE"
    elif major == "MSE/ME Joint Major":
        ce.loc[i, "Major"] = "MSE/ME"
    elif major == "MSE/NE Joint Major":
        ce.loc[i, "Major"] = "MSE/NE"

In [122]:
ce = ce[(ce['Major'] != "MSE/NE") & (ce['Major'] != "MSE/ME") & (ce['Major'] != 'ME/NE') & (ce['Major'] != 'EECS/MSE') & (ce['Major'] != 'EECS/NE') & (ce['Major'] != 'BioE/MSE')]

In [123]:
gender_grouped = ce.groupby(by=["Academic Yr", "Major", "Gender Desc"]
                  ).sum().drop('Prorated Degrees Awarded Cnt', axis=1)

In [125]:
year_majors = []
for i in gender_grouped.index:
    i = i[:2]
    year_majors.append(i)
year_majors

[('2014-15', 'BioE'),
 ('2014-15', 'BioE'),
 ('2014-15', 'CivE'),
 ('2014-15', 'CivE'),
 ('2014-15', 'EECS'),
 ('2014-15', 'EECS'),
 ('2014-15', 'EnergyE'),
 ('2014-15', 'EnergyE'),
 ('2014-15', 'EngMathStats'),
 ('2014-15', 'EngPhys'),
 ('2014-15', 'EngPhys'),
 ('2014-15', 'Environmental Eng Science'),
 ('2014-15', 'Environmental Eng Science'),
 ('2014-15', 'IEOR'),
 ('2014-15', 'IEOR'),
 ('2014-15', 'Materials Science & Eng'),
 ('2014-15', 'Materials Science & Eng'),
 ('2014-15', 'Mechanical Engineering'),
 ('2014-15', 'Mechanical Engineering'),
 ('2014-15', 'Nuclear Engineering'),
 ('2014-15', 'Nuclear Engineering'),
 ('2015-16', 'BioE'),
 ('2015-16', 'BioE'),
 ('2015-16', 'CivE'),
 ('2015-16', 'CivE'),
 ('2015-16', 'EECS'),
 ('2015-16', 'EECS'),
 ('2015-16', 'EnergyE'),
 ('2015-16', 'EnergyE'),
 ('2015-16', 'EngMathStats'),
 ('2015-16', 'EngMathStats'),
 ('2015-16', 'EngPhys'),
 ('2015-16', 'EngPhys'),
 ('2015-16', 'Environmental Eng Science'),
 ('2015-16', 'IEOR'),
 ('2015-16', 'IEOR'),
 ('2015-16', 'Materials Science & Eng'),
 ('2015-16', 'Materials Science & Eng'),
 ('2015-16', 'Mechanical Engineering'),
 ('2015-16', 'Mechanical Engineering'),
 ('2015-16', 'Nuclear Engineering'),
 ('2015-16', 'Nuclear Engineering'),
 ('2016-17', 'BioE'),
 ('2016-17', 'BioE'),
 ('2016-17', 'CivE'),
 ('2016-17', 'CivE'),
 ('2016-17', 'EECS'),
 ('2016-17', 'EECS'),
 ('2016-17', 'EECS'),
 ('2016-17', 'EnergyE'),
 ('2016-17', 'EnergyE'),
 ('2016-17', 'EngMathStats'),
 ('2016-17', 'EngMathStats'),
 ('2016-17', 'EngPhys'),
 ('2016-17', 'EngPhys'),
 ('2016-17', 'Environmental Eng Science'),
 ('2016-17', 'Environmental Eng Science'),
 ('2016-17', 'IEOR'),
 ('2016-17', 'IEOR'),
 ('2016-17', 'Materials Science & Eng'),
 ('2016-17', 'Materials Science & Eng'),
 ('2016-17', 'Mechanical Engineering'),
 ('2016-17', 'Mechanical Engineering'),
 ('2016-17', 'Nuclear Engineering'),
 ('2016-17', 'Nuclear Engineering'),
 ('2017-18', 'BioE'),
 ('2017-18', 'BioE'),
 ('2017-18', 'CivE'),
 ('2017-18', 'CivE'),
 ('2017-18', 'CivE'),
 ('2017-18', 'EECS'),
 ('2017-18', 'EECS'),
 ('2017-18', 'EECS'),
 ('2017-18', 'EnergyE'),
 ('2017-18', 'EnergyE'),
 ('2017-18', 'EngMathStats'),
 ('2017-18', 'EngMathStats'),
 ('2017-18', 'EngPhys'),
 ('2017-18', 'EngPhys'),
 ('2017-18', 'Environmental Eng Science'),
 ('2017-18', 'Environmental Eng Science'),
 ('2017-18', 'IEOR'),
 ('2017-18', 'IEOR'),
 ('2017-18', 'Materials Science & Eng'),
 ('2017-18', 'Materials Science & Eng'),
 ('2017-18', 'Mechanical Engineering'),
 ('2017-18', 'Mechanical Engineering'),
 ('2017-18', 'Mechanical Engineering'),
 ('2017-18', 'Nuclear Engineering'),
 ('2017-18', 'Nuclear Engineering'),
 ('2018-19', 'BioE'),
 ('2018-19', 'CivE'),
 ('2018-19', 'EECS'),
 ('2018-19', 'EECS'),
 ('2018-19', 'EnergyE'),
 ('2018-19', 'EngMathStats'),
 ('2018-19', 'EngPhys'),
 ('2018-19', 'Environmental Eng Science'),
 ('2018-19', 'Materials Science & Eng'),
 ('2018-19', 'Materials Science & Eng'),
 ('2018-19', 'Mechanical Engineering'),
 ('2018-19', 'Mechanical Engineering'),
 ('2018-19', 'Nuclear Engineering')]

In [126]:
gender_grouped = gender_grouped.reset_index()

In [127]:
major = list(year_majors[0])
major + ['Decline to State', 0]

['2014-15', 'BioE', 'Decline to State', 0]

In [129]:
j = 103
for i in year_majors:
    major = list(i)
    gender_grouped.loc[j] = major + ['Decline to State', 0]
    j += 1
    gender_grouped.loc[j] = major + ['Female', 0]
    j += 1
    gender_grouped.loc[j] = major + ['Male', 0]
    j += 1

In [130]:
gender_grouped.tail()

    Academic Yr                   Major       Gender Desc  Student Headcount
407     2018-19  Mechanical Engineering            Female                  0
408     2018-19  Mechanical Engineering              Male                  0
409     2018-19     Nuclear Engineering  Decline to State                  0
410     2018-19     Nuclear Engineering            Female                  0
411     2018-19     Nuclear Engineering              Male                  0

In [134]:
gender_grouped = gender_grouped.groupby(by=["Academic Yr", "Major", "Gender Desc"]).sum()
gender_grouped

                                                        Student Headcount
Academic Yr Major                     Gender Desc
2014-15     BioE                      Decline to State                  0
                                      Female                           35
                                      Male                             64
            CivE                      Decline to State                  0
                                      Female                           22
                                      Male                             46
            EECS                      Decline to State                  0
                                      Female                           51
                                      Male                            316
            EnergyE                   Decline to State                  0
                                      Female                            1
                                      Male                              1
            EngMathStats              Decline to State                  0
                                      Female                            0
                                      Male                              7
            EngPhys                   Decline to State                  0
                                      Female                            2
                                      Male                             14
            Environmental Eng Science Decline to State                  0
                                      Female                            6
                                      Male                              7
            IEOR                      Decline to State                  0
                                      Female                           13
                                      Male                             27
            Materials Science & Eng   Decline to State                  0
                                      Female                           10
                                      Male                             13
            Mechanical Engineering    Decline to State                  0
                                      Female                           13
                                      Male                            155
...                                                                   ...
2018-19     BioE                      Decline to State                  0
                                      Female                            1
                                      Male                              0
            CivE                      Decline to State                  0
                                      Female                            0
                                      Male                              2
            EECS                      Decline to State                  0
                                      Female                            3
                                      Male                             17
            EnergyE                   Decline to State                  0
                                      Female                            0
                                      Male                              1
            EngMathStats              Decline to State                  0
                                      Female                            0
                                      Male                              1
            EngPhys                   Decline to State                  0
                                      Female                            0
                                      Male                              1
            Environmental Eng Science Decline to State                  0
                                      Female                            0
                                      Male                              1
            Materials Science & Eng   Decline to State                  0
                                      Female                            1
                                      Male                              1
            Mechanical Engineering    Decline to State                  0
                                      Female                            4
                                      Male                              5
            Nuclear Engineering       Decline to State                  0
                                      Female                            0
                                      Male                              3

[162 rows x 1 columns]

In [137]:
year_majors = []
for i in np.arange(0, len(gender_grouped), 3):
    major = gender_grouped.index[i][:2]
    year_majors.append(major)

In [143]:
gender_grouped = gender_grouped.reset_index()

In [162]:
from bokeh.core.properties import value
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.plotting import figure
output_file("bar_stacked_grouped.html")

factors = year_majors

regions = ['dts', 'female', 'male']

source = ColumnDataSource(data=dict(
    x=factors,
    dts=gender_grouped.loc[gender_grouped['Gender Desc'] == 'Decline to State', 'Student Headcount'],
    female=gender_grouped.loc[gender_grouped['Gender Desc'] == 'Female', 'Student Headcount'],
    male=gender_grouped.loc[gender_grouped['Gender Desc'] == 'Male', 'Student Headcount']
))

p = figure(x_range=FactorRange(*factors), plot_height=750, plot_width = 1500,
           toolbar_location=None, tools="hover", tooltips="$name: @$name")

p.vbar_stack(regions, x='x', width=0.9, alpha=0.5, color=["purple","red", "blue"], source=source,
             legend=[value(x) for x in regions])

#p.y_range.start = 0
#p.y_range.end = 18
p.x_range.range_padding = 0.5
p.xaxis.major_label_orientation = 1
p.xgrid.grid_line_color = None
p.legend.location = "top_center"
p.legend.orientation = "horizontal"

show(p)